theme: jekyll-theme-minimal

# https://github.com/pages-themes/minimal
# variables:
# https://github.com/jekyll/github-metadata/blob/master/docs/site.github.md

title: Open Hospitality Network
email: hospexsummit@gmail.com
description: We try to federate different hospitality exchange platforms to unify the community while enabling greater diversity and long term sustainability of all together.
baseurl: ''
url: https://OpenHospitalityNetwork.github.io
#twitter_username: Your Twitter username (do not include @ symbol).
github_username: OpenHospitalityNetwork
google_analytics: UA-199347194-1

markdown: kramdown
kramdown:
  input: GFM

plugins:
    - jekyll-seo-tag
