# SPDX-FileCopyrightText: 2022 Maria Kozinska <m.kozinska@gmail.com>
# SPDX-FileCopyrightText: 2022 Open Hospitality Network
#
# SPDX-License-Identifier: AGPL-3.0-only


name: Notify matrix when a discussion is started

on:
  discussion:
      types: [created, transferred]

jobs:
  ping_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: send message for a discussion
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "${{ github.event.discussion.user.login }} has just opened an issue: [${{ github.event.discussion.title }}](${{ github.event.discussion.html_url }})"
          server: "matrix.org"
